name: Update submodule
on:
  push:
    branches: [ docker-build-fix-patch-1 ]

jobs:
  update-submodule:
    name: Update Houston's submodule to latest develop
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          repository: 'https://github.com/WildMeOrg/houston.git'
          submodules: true
          # persist-credentials: false 
          # fetch-depth: 0  
          token: ${{ secrets.PAT_TOKEN }}
    
      - run: |
          bash -xe <<EOF
          echo ${{ github.actor }}
          git config user.name github-actions
          git config user.email github-actions@github.com
          cd _frontend.codex
          git reset --hard origin/develop
          cd ..
          git commit -am 'Update _frontend.codex submodule to HEAD of codex-frontend@develop'
          git show
          git push origin HEAD
          EOF
